language: objective-c

cache: bundler

rvm:
  - 2.0.0

script:
    - bundle exec rake build
    - sudo gem install ./pkg/kitchenplan*
    - kitchenplan setup --gitrepo https://github.com/kitchenplan/kitchenplan-config-test.git
    - kitchenplan provision --debug
#    - sudo rake test
