groups:
    - bash
    - developer
recipes:
    global:
    mac_os_x:
        - applications::1password
        - applications::cask_apps
        - applications::charlesproxy
        - applications::dropbox
        - applications::evernote
        - applications::istatmenus4
        - applications::kaleidoscope
        - applications::things
        - applications::tower
        - applications::vlc
        - applications::alfred
        - applications::cord
        - applications::transmit
        - applications::bartender

        # dotfiles for projects - attributes defined below
        - dotfiles::projects

        # osxdefaults
        - osxdefaults::set_computer_name

attributes:
    brew:
        cask_apps:
            - jing
    sublime_text:
        preferences:
            font_size: 14
            ignored_packages: []
            remember_open_files: false
            tab_size: 2
            vintage_start_in_command_mode: true
            vintage_use_clipboard: true
    git:
        name: Tega McKinney
        email: tega.mckinney@freshedgesolutions.com
    osxdefaults:
        computername: Snoopy
    dotfiles:
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
        projects:
            -
                - kitchenplan
                - https://github.com/tegamckinney/kitchenplan.git
            -
                - chef-applications
                - https://github.com/tegamckinney/chef-applications.git
            -
                - mackup
                - https://github.com/tegamckinney/mackup.git
            -
                - neglectedbytes
                - https://github.com/tegamckinney/neglectedbytes
