recipes:
    global:
        - applications::bash-completion
        - dotfiles::bash_it
        - dotfiles::inputrc

attributes:
	bash_it:
	    theme: tylenol
	    enabled_plugins:
	      completion:
	        - defaults
	        - bash-it
	        - git
	        - brew
	        - gem
	        - rake
	        - ssh
	      plugins:
	        - git
	        - ssh
	        - ruby
