recipes:
    global:
        - applications::git
        - applications::wget
        - applications::pwgen
        - applications::xmlstarlet
        - applications::pv
        - applications::htop
        - applications::grunt-cli
        - applications::git-flow
        - applications::sass
        - applications::siege
        - applications::nodejs
        - applications::ssh_config
        - applications::composer
        - applications::postgresql
        - applications::psycopg2
        - applications::mysql
        - applications::mysql_python
        - applications::php55
        - applications::tmux

        # dotfiles
        - dotfiles::gitconfig
        - dotfiles::vim
        - dotfiles::workspace
        - dotfiles::gem_setup

    mac_os_x:
        - applications::codekit
        - applications::github_for_mac
        - applications::gnu-tar
        - applications::heroku
        - applications::imageoptim
        - applications::imagealpha
        - applications::iterm2
        - applications::mou
        - applications::phantomjs
        - applications::rvm
        - applications::sequelpro
        - applications::svgo
        - applications::sublime_text_3
        - applications::sourcetree
        - applications::virtualbox
        - applications::watch

        # osx defaults for developers
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
attributes:
    mysql_root_password: "password"
